### ISSUE TITLE
Unable to Create playlists

### ISSUE THREAD

**Issue by kronckers** [kevhal-11/Deezer-to-Spotify-playlist_converter#2]
Hi, firstly thanks for taking the time to look into making this, would rather have this than the paid websites. I have encountered a weird issue, where I have managed to successfully copy over one playlist, but then doing others afterwards have stopped working. Gives the "Sorry, there has been a problem creating your playlist" error after only half a second.

The playlist has been created in Spotify, but nothing is copied across. I then went back to do the one I had working, which no longer copies across! I'm by no means proficient in Python, but having a look around I *think* it might be that the deezer-python module isn't using the oauth key properly. I'm able to manually get the key [from this](https://stackoverflow.com/questions/60166334/deezer-api-access-token) and use that on the API explorer on Deezer's website to get the raw playlist data. The speed of the error makes me thing Deezer is returning token invalid, but then again the fact it worked once is weird!

Sorry if that's not very helpful, I'm not an expert :)

**Comment by kevhall11** [comment]
Hey there the issue is within the PlaylistConverter.main() file because a 0 is being returned which is what is giving you the really fast response time for that. I do not currently have the time to work on it but I will sometime this week, If you have any other recommendations please let me know!

**Comment by kevhall11** [comment]
If you are dealing with large playlists the google token that is given will time out due to the program spamming google. To resolve this you must delete what I believe is the index file or whatever file is created when the program is first ran. I believe this file holds just a token.
